### ISSUE TITLE
fail evaluation

### ISSUE THREAD

**Issue by ldggggg** [hjwdzh/PrimitiveNet#1]
Dear Jingwei,

Thanks for releasing the code. I tried to evaluate the ABC dataset. But I got errors shown in below:

```
> /home/ubuntu/primitivenet/PrimitiveNet/src/util/config.py:19: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
>   config = yaml.load(f)
> [2021-10-19 15:03:01,872  INFO  log.py  line 40  8783]  ************************ Start Logging ************************
> [2021-10-19 15:03:01,967  INFO  test_boundary.py  line 190  8783]  => creating model ...
> [2021-10-19 15:03:02,059  INFO  test_boundary.py  line 195  8783]  cuda available: True
> [2021-10-19 15:03:04,608  INFO  utils.py  line 61  8783]  Restore from ../checkpoints/abc.pth
> Traceback (most recent call last):
>   File "test_boundary.py", line 202, in <module>
>     start_epoch = utils.checkpoint_restore(model, cfg.exp_path, cfg.config.split('/')[-1][:-5], use_cuda, 0, False, cfg.pretrain)
>   File "/home/ubuntu/primitivenet/PrimitiveNet/src/util/utils.py", line 62, in checkpoint_restore
>     checkpoint = torch.load(f)
>   File "/usr/local/lib/python3.8/dist-packages/torch/serialization.py", line 601, in load
>     if _is_torchscript_zip(opened_zipfile):
>   File "/usr/local/lib/python3.8/dist-packages/torch/serialization.py", line 890, in _is_torchscript_zip
>     return 'constants.pkl' in zip_file.get_all_records()
> RuntimeError: [enforce fail at inline_container.cc:230] . file in archive is not in a subdirectory archive/: checkpoints/scene.pth
> /usr/lib/python3/dist-packages/numpy/core/fromnumeric.py:3256: RuntimeWarning: Mean of empty slice.
>   return _methods._mean(a, axis=axis, dtype=dtype,
> /usr/lib/python3/dist-packages/numpy/core/_methods.py:161: RuntimeWarning: invalid value encountered in double_scalars
>   ret = ret.dtype.type(ret / rcount)
> Traceback (most recent call last):
>   File "eval_ap.py", line 175, in <module>
>     num_true_examples = y_true_sorted_cumsum[-1]
> IndexError: index -1 is out of bounds for axis 0 with size 0
```

I guess the problem comes from the pre-trained models that you provided. I don't understand why there is a 'scenc.pth' instead of 'abc.pth' in the Zip archive "abc.pth".

Thanks in advance and looking forwards to your respond.

Best and have a nice day.

**Comment by MulinYu** [comment]
Same problem here, have you fixed it?

**Comment by hjwdzh** [comment]
Did you find abc-pretrained.pth and scene.pth? Put them into the checkpoints folder, and other data in the data foler.
In my setting, the files are organized as below:

PrimitiveNet (checkpoints, data, scripts, src)
checkpoints (abc-pretrained.pth, scene.pth)
data (ABC, Scene)
scripts (...)
src (...)

**Comment by hjwdzh** [comment]
Though it is closed, I need to mention that my abc.pth is broken. You can retrain it yourself, or please wait for 3-5 days for me to upload a new one:)

**Comment by hjwdzh** [comment]
Please view the new link in download.sh.
